<title><?php echo $this->pageTitle = 'お問い合わせ ｜ 該非判定WEBシステム ｜ 株式会社ディスコ'; ?>
</title>
<div id="contents" class="inquiry morefooterspace text03m">
	<div class="inquirycontents">
		<form id="inquiry" method="post">
			<h2>メールでお問い合わせ</h2>
			<p>
			<?php echo $this->formButton('btContact', 'お問い合わせ専用フォームを開く', array('class' => 'zbtn_short1', 'onclick'=> '')); ?>
			</p>
		</form>
	</div>
	<div class="inquirycontents">
		<h2>電話でお問い合わせ</h2>
		<div class="address">
			<p>
				株式会社ディスコ<br> 品質保証部・輸出管理担当
			</p>
			<p>TEL：03-4590-1064</p>
		</div>
	</div>
</div>
<script type="text/javascript">
    var wnds = new Array();
    $('#btContact').click(function(){
        var id = this.id;
        for(i = 0; i < wnds.length; ++i)
            wnds[i].close();
        wnds[wnds.length] = window.open("/inquiry/form");
    });
    
</script>
