<legend>Về chúng tôi</legend>
<p>
Trong những năm gần đây, trắc nghiệm đã trở thành hình thức thi cử chính ở nước ta. <br>
Hầu hết các kỳ thi từ bậc tiểu học cho đến đại học đều có đưa vào hình thức thi này, đặc biệt <br>
là đối với học sinh cấp 3. Nắm bắt tình hình đó, chúng tôi đã tạo ra một kho đề thi trắc nghiệm <br>
với một số lượng khá lớn những câu hỏi trong chương trình học phổ thông nhằm giúp các em, đặc biệt<br>
là những em không có điều kiện đến các cơ sở ôn thi, hệ thống lại một cách đầy đủ nhất những gì <br>
mình đã được học, để các em có được sự chuẩn bị tốt nhất cho kỳ thi quan trọng nhất trong đời mình - <br>
thi đại học.
</p>
<br>
Tác giả: Anh Nguyễn<br>
Số điện thoại liên hệ: 0169.680.3198<br>
Email: anhnv1310@gmail.com<br>
Facebook: facebook.com/van.anh1310
