<nav class="navigation-bar dark">
	<nav class="navigation-bar-content">
		<div class="no-tablet-portrait">
			<div class="element">
				<a href="#"><span class="icon-home"></span></a>
			</div>
			<span class="element-divider"></span>			
			<div class="element">
				<div class="input-control text">
				    <input type="text" />
				    <button class="btn-search"></button>
				</div>
			</div>
        	<div class="element place-right">
            	<a class="dropdown-toggle" href="#">
            		<span class="icon-cog"></span>
            	</a>
                <ul class="dropdown-menu place-right" data-role="dropdown" data-effect='fade'>
                	<li><a href="#">Thông tin cá nhân</a></li>
                    <li><a href="#">Đổi mật khẩu</a></li>
                    <li><a href="#">Đăng xuất</a></li>
                </ul>
			</div>
            <span class="element-divider place-right"></span>
            <button class="element image-button image-left place-right">
            	Anh Nguyễn
            	<img src="/resources/metro/images/me.jpg"/>
            </button>
		</div>		
	</nav>
</nav>