<nav class="horizontal-menu">
    <ul>
        <li>
        	<a class="dropdown-toggle" href="#">Products</a>
        	<ul class="dropdown-menu dark" data-show="hover">
        		<li><a href="#">Windows 8.1</a></li>
        		<li><a href="#">Skype 20.0</a></li>
        		<li><a href="#">Internet Explorer 14</a></li>
        		<li><a href="#">Microsoft Office 14</a></li>
        	</ul>
        </li>
        <li><a href="#">Download</a></li>
        <li><a href="#">Support</a></li>
        <li><a href="#">Buy Now</a></li>
    </ul>
</nav>