<nav class="horizontal-menu">
    <ul>
        <li>
        	<a class="dropdown-toggle" href="#">Vật lý</a>
        	<ul class="dropdown-menu dark opacity" data-show="hover">
        		<li><a href="#">Lớp 10</a></li>
        		<li><a href="#">Lớp 11</a></li>
        		<li><a href="#">Lớp 12</a></li>
        	</ul>
        </li>
        <li>
        	<a class="dropdown-toggle" href="#">Hóa học</a>
        	<ul class="dropdown-menu dark opacity" data-show="hover">
        		<li><a href="#">Lớp 10</a></li>
        		<li><a href="#">Lớp 11</a></li>
        		<li><a href="#">Lớp 12</a></li>
        	</ul>
        </li>
        <li>
        	<a class="dropdown-toggle" href="#">Sinh học</a>
        	<ul class="dropdown-menu dark opacity" data-show="hover">
        		<li><a href="#">Lớp 10</a></li>
        		<li><a href="#">Lớp 11</a></li>
        		<li><a href="#">Lớp 12</a></li>
        	</ul>
        </li>
        <li>
        	<a class="dropdown-toggle" href="#">Tiếng Anh</a>
        	<ul class="dropdown-menu dark opacity" data-show="hover">
        		<li><a href="#">Lớp 10</a></li>
        		<li><a href="#">Lớp 11</a></li>
        		<li><a href="#">Lớp 12</a></li>
        	</ul>
        </li>
        <li>
        	<a href="#">Thi thử đại học</a>
        </li>
    </ul>
</nav>