<div class="accordion with-marker span3 place-left margin10" data-role="accordion" data-closeany="false">
<div class="accordion-frame">
	<a class="heading bg-lightBlue fg-white" href="/admin/submajor/add">Thêm lĩnh vực con</a>
</div>
</div>

<div class="accordion with-marker span3 place-left margin10" data-role="accordion" data-closeany="false">
<div class="accordion-frame">
	<a class="heading bg-lightBlue fg-white" href="/admin/question/add">Thêm câu hỏi</a>
</div>
</div>