<form action="/register/do-register" method="post">
<fieldset>
	<legend>Đăng ký tài khoản</legend>
    <label>Tên đăng nhập&nbsp;<span class="required">*</span></label>
    <div class="input-control text size4" data-role="input-control">
    	<?php echo $this->formText('username', '', array('placeholder' => 'type text')); ?>
    </div>
    <label>Mật khẩu&nbsp;<span class="required">*</span></label>
    <div class="input-control password size4" data-role="input-control">
    	<?php echo $this->formText('password', '', array('placeholder' => 'type password')); ?>
	</div>
    <div class="input-control text size4" data-role="input-control">
    	<?php echo $this->formText('retype-password', '', array('placeholder' => 're-type password')); ?>
	</div>
    <label>Lớp&nbsp;<span class="required">*</span></label>
    <div class="input-control select size4">
    	<?php //echo $this->formSe?>
		<select>
			<option>Lớp 10</option>
			<option>Lớp 11</option>
			<option>Lớp 12</option>
		</select>
	</div>
	<label>Email</label>
	<div class="input-control text size4">
		<?php echo $this->formText('email', '', array('placeholder' => 'type email'));?>
	</div>
	<label>Số điện thoại</label>
	<div class="input-control text size4">
		<?php echo $this->formText('phone-number', '', array('placeholder' => 'type phone number'));?>
	</div>

    <div class="clearfix"></div>

    <input type="submit" value="Đăng ký">
    <input type="reset" value="Nhập lại">

    <div style="margin-top: 20px"></div>

</fieldset>                    
</form>                