<legend>Đăng ký tài khoản thành công!</legend>

<div class="line-height-200">
Chúc mừng bạn đã đăng ký thành công tài khoản tại <a href="/home">tracnghiemcap3.com</a><br>
Chúng tôi đã gửi một mail kích hoạt đến hòm thư của bạn, 
bạn vui lòng kiểm tra lại hòm thư để kích hoạt tài khoản.
</div>

<div class="sign">
BQT tracnghiemcap3.com
</div>

<div class="back-to-home">
<a href="/home">Quay lại trang chủ</a>
</div>
