<form id="registerForm" action="/register/confirm-register" method="post">
<fieldset>
	<legend>Đăng ký tài khoản</legend>
    <label>Tên đăng nhập&nbsp;<span class="required">*</span></label>
    <div class="input-control text size4" data-role="input-control">
    	<?php echo $this->formText('username', $this->request->username, array('placeholder' => 'type text')); ?>
    	<?php echo $this->formError('username');?>
    </div>
    <label class="col-lg-3 control-label">Mật khẩu&nbsp;<span class="required">*</span></label>
    <div class="input-control password size4" data-role="input-control">
        <input type="password" name="password" />
    	<?php echo $this->formPassword('password', $this->request->password, array('placeholder' => 'type password')); ?>
    	<?php echo $this->formError('password');?>
	</div>
	<label class="col-lg-3 control-label">Xác nhận mật khẩu&nbsp;<span class="required">*</span></label>
    <div class="input-control password size4" data-role="input-control">
    	<?php echo $this->formPassword('retype_password', $this->request->retype_password, array('placeholder' => 're-type password')); ?>
    	<?php echo $this->formError('retype_password');?>
	</div>
    <label>Lớp&nbsp;<span class="required">*</span></label>
    <div class="input-control select size4">
    	<?php echo $this->formSelect('class_id', null, null, $this->classes);?>
	</div>
	<label>Email&nbsp;<span class="required">*</span></label>
	<div class="input-control text size4">
		<?php echo $this->formText('email', $this->request->email, array('placeholder' => 'type email'));?>
		<?php echo $this->formError('email'); ?>
	</div>
	<label>Số điện thoại</label>
	<div class="input-control text size4">
		<?php echo $this->formText('phone', $this->request->phone, array('placeholder' => 'type your phone'));?>
		<?php echo $this->formError('phone');?>
	</div>

	<div class="clearfix"></div>
    <div class="space15"></div>

    <input type="submit" class="info" value="Đăng ký">&nbsp;&nbsp;
    <input type="reset" class="info" value="Nhập lại">

    <div style="margin-top: 20px"></div>

</fieldset>                    
</form>

<form id="registerForm1" class="form-horizontal1">
    <div class="form-group1">
        <label class="col-lg-3 control-label1">Password</label>
        <div class="col-lg-51">
            <input type="password" name="password" />
        </div>
    </div>

<!--     <div class="form-group"> -->
        <label class="col-lg-3 control-label1">Retype password</label>
<!--         <div class="col-lg-5"> -->
            <input type="password" class="form-control" name="retype_password" />
<!--         </div> -->
<!--     </div> -->
</form>

<script type="text/javascript">
$(document).ready(function() {
    $('#registerForm').bootstrapValidator({
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            password: {
                validators: {
                    identical: {
                        field: 'retype_password',
                        message: 'The password and its confirm are not the same'
                    }
                }
            },
            retype_password: {
                validators: {
                    identical: {
                        field: 'password',
                        message: 'The password and its confirm are not the same'
                    }
                }
            }
        }
    });
});
</script>