<form action="/register/confirm-register" method="post">
<fieldset>
	<legend>Đăng ký tài khoản</legend>
    <label>Tên đăng nhập&nbsp;<span class="required">*</span></label>
    <div class="input-control text size4" data-role="input-control">
    	<?php echo $this->formText('username', $this->request->username, array('placeholder' => 'type text')); ?>
    	<?php echo $this->formError('username');?>
    </div>
    <label>Mật khẩu&nbsp;<span class="required">*</span></label>
    <div class="input-control password size4" data-role="input-control">
    	<?php echo $this->formPassword('password', $this->request->password, array('placeholder' => 'type password')); ?>
    	<?php if ($this->formError('password') == null):?>
    		<span style="visibility: hidden">&nbsp;</span>
    	<?php endif;?>
    	<?php echo $this->formError('password');?>
	</div>
    <div class="input-control password size4" data-role="input-control">
    	<?php echo $this->formPassword('retype_password', $this->request->retype_password, array('placeholder' => 're-type password')); ?>
    	<?php if ($this->formError('retype_password') == null):?>
    		<span style="visibility: hidden">&nbsp;</span>
    	<?php endif;?>
    	<?php echo $this->formError('retype_password');?>
	</div>
    <label>Lớp&nbsp;<span class="required">*</span></label>
    <div class="input-control select size4">
    	<?php //echo $this->formSe?>
		<select name="class_id">
			<option value="10">Lớp 10</option>
			<option value="11">Lớp 11</option>
			<option value="12">Lớp 12</option>
		</select>
	</div>
	<label>Email&nbsp;<span class="required">*</span></label>
	<div class="input-control text size4">
		<?php echo $this->formText('email', $this->request->email, array('placeholder' => 'type email'));?>
		<?php echo $this->formError('email'); ?>
	</div>
	<label>Số điện thoại</label>
	<div class="input-control text size4">
		<?php echo $this->formText('phone', $this->request->phone, array('placeholder' => 'type your phone'));?>
		<?php echo $this->formError('phone');?>
	</div>

	<div class="clearfix"></div>
	
    <div class="clearfix"></div>

    <input type="submit" class="info" value="Đăng ký">
    <input type="reset" class="info" value="Nhập lại">

    <div style="margin-top: 20px"></div>

</fieldset>                    
</form>
