<form id="registerForm" action="/register/confirm-register" method="post">
<fieldset>
	<legend>Đăng ký tài khoản</legend>
    <label>Tên đăng nhập&nbsp;<span class="required">*</span></label>
    <div class="input-control text size4" data-role="input-control">
    	<?php echo $this->formText('username', $this->request->username, array('placeholder' => 'type text')); ?>
    	<?php echo $this->formError('username');?>
    </div>
    <label class="col-lg-3 control-label">Mật khẩu&nbsp;<span class="required">*</span></label>
    <div class="input-control password size4" data-role="input-control">
    	<?php echo $this->formPassword('password', $this->request->password, array('placeholder' => 'type password')); ?>
    	<?php echo $this->formError('password');?>
	</div>
	<label class="col-lg-3 control-label">Xác nhận mật khẩu&nbsp;<span class="required">*</span></label>
    <div class="input-control password size4" data-role="input-control">
    	<?php echo $this->formPassword('retype_password', $this->request->retype_password, array('placeholder' => 're-type password')); ?>
    	<?php echo $this->formError('retype_password');?>
	</div>
    <label>Lớp&nbsp;<span class="required">*</span></label>
    <div class="input-control select size4">
    	<?php echo $this->formSelect('class_id', null, null, $this->classes);?>
	</div>
	<label>Email&nbsp;<span class="required">*</span></label>
	<div class="input-control text size4">
		<?php echo $this->formText('email', $this->request->email, array('placeholder' => 'type email'));?>
		<?php echo $this->formError('email'); ?>
	</div>
	<label>Số điện thoại</label>
	<div class="input-control text size4">
		<?php echo $this->formText('phone', $this->request->phone, array('placeholder' => 'type your phone'));?>
		<?php echo $this->formError('phone');?>
	</div>

	<div class="clearfix"></div>
    <div class="space15"></div>

    <input id="submitBtn" type="submit" class="info" value="Đăng ký">&nbsp;&nbsp;
    <input type="reset" class="info" value="Nhập lại">

    <div style="margin-top: 20px"></div>

</fieldset>                    
</form>

<script type="text/javascript">
$(document).ready(function() {
    $('#submitBtn').click(function(){
        var psw = $('#password').val();
        var confirmPsw = $('#retype_password').val();

        if (psw != confirmPsw) {
			alert('Mật khẩu xác nhận không đúng!');
			return false;
        }
    });
});
</script>