<!-- <form action="auth/confirm-login" method="post"> -->
<form action="/auth/confirm-login" method="post">
	<fieldset>
		<legend>Đăng nhập</legend>
		<label>Tên đăng nhập</label>
		<div class="input-control text size3" data-role="input-control">
			<?php echo $this->formText('username', '', array('placeholder' => 'User name'));?>
			<?php echo $this->formError('username');?>
<!-- 			<button class="btn-clear" tabindex="-1"></button> -->
		</div>
		<label>Mật khẩu</label>
		<div class="input-control password size3" data-role="input-control">
			<?php echo $this->formPassword('password', $this->password, array('placeholder' => 'Your password'))?>
			<?php echo $this->formError('password');?>
<!-- 			<button class="btn-reveal" tabindex="-1"></button> -->
		</div>
		<div class="input-control textbox" data-role="input-control">
			<label>
				<?php echo $this->formCheckbox('remember', $this->remember, array('checked' => false));?>
				<span class="check"></span>
				Ghi nhớ?
			</label>
		</div>
		<br>
		<div style="line-height: 200%">
			<input type="submit" class="info" value="Đăng nhập">
		</div>
	</fieldset>
</form>