<form action="/recover/confirm-recover" method="post">
<fieldset>
	<legend>Lấy lại mật khẩu</legend>
	<div align="center" class="center-text">
		Hãy nhập chính xác địa chỉ email mà bạn đã dùng để đăng ký tài khoản tại <a href="tracnghiemcap3.com">tracnghiemcap3.com</a>,
		<br>chúng tôi sẽ gửi lại mã kích hoạt cho bạn.<br><br>
	    Email&nbsp;<span class="required">*</span>&nbsp;
	    <div class="input-control text size5" data-role="input-control">
	    	<?php echo $this->formText('email', $this->request->username, array('placeholder' => 'type email')); ?>
	    	<?php echo $this->formError('email');?>
	    </div>
	    <div>
	    	<input type="submit" class="info" value="Lấy lại mật khẩu">
		</div>
    </div>
</fieldset>                    
</form>