<nav class="horizontal-menu">
    <ul>
        <li>
        	<a class="dropdown-toggle" href="#">Quản lý câu hỏi</a>
        	<ul class="dropdown-menu dark opacity" data-show="hover">
        		<li><a href="#">Tiếng Anh</a></li>
        		<li><a href="#">Vật lý</a></li>
        		<li><a href="#">Hóa học</a></li>
        		<li><a href="#">Sinh học</a></li>
        		<li><a href="#">Địa lý</a></li>
        	</ul>
        </li>
        <li>
        	<a class="dropdown-toggle" href="#">Quản lý người dùng</a>
        	<ul class="dropdown-menu dark opacity" data-show="hover">
        		<li><a href="#">Danh sách người dùng</a></li>
<!--         		<li><a href="#">Lớp 11</a></li> -->
<!--         		<li><a href="#">Lớp 12</a></li> -->
        	</ul>
        </li>
        <!-- More menus go here -->
    </ul>
</nav>