<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<!-- CSS -->
	<link type="text/css" rel="stylesheet" href="/resources/metro/css/metro-bootstrap.css">
	<link type="text/css" rel="stylesheet" href="/resources/metro/css/metro-bootstrap-responsive.css">
	<link type="text/css" rel="stylesheet" href="/resources/metro/min/iconFont.min.css" >
	<link type="text/css" rel="stylesheet" href="/resources/styles/layout.css">
	<link type="text/css" rel="stylesheet" href="/resources/styles/common.css">
	<!-- JS -->
	<script type="text/javascript" src="/resources/metro/js/metro-dropdown.js"></script>
	<script type="text/javascript" src="/resources/metro/js/metro-input-control.js"></script>
	<script type="text/javascript" src="/resources/scripts/jquery.easing.1.3.min.js"></script>
	<script type="text/javascript" src="/resources/scripts/jquery-1.8.2.js" ></script>
	<script type="text/javascript" src="/resources/scripts/jquery.countdownTimer.js" ></script>
</head>

<!-- BODY -->
<body class="metro">
	<?php echo $this->render('_partial/header.phtml');?>
	<?php echo $this->render('_partial/menu.phtml');?>
	<br>
	<!-- CONTENT -->
	<div class="wrapper">
		<div class="container">
			<div class="main-cont.ent clearfix">
	            <?php echo $this->layout()->content;?>
	        </div> <!-- End of tiles -->
		</div> <!-- container -->
		<div class="push"></div>
	</div>
	<div class="footer">
		<?php echo $this->render('_partial/footer.phtml');?>
	</div>
</body>
</html>

