<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<!-- CSS -->
	<link type="text/css" rel="stylesheet" href="/resources/metro/css/metro-bootstrap.css">
	<link type="text/css" rel="stylesheet" href="/resources/metro/css/metro-bootstrap-responsive.css">
	<link type="text/css" rel="stylesheet" href="/resources/metro/min/iconFont.min.css" >
	<!-- JS -->
	<script type="text/javascript" src="/resources/metro/js/metro-dropdown.js"></script>
</head>

<!-- BODY -->
<body class="metro">
	<?php echo $this->render('_partial/header.phtml');?>
	<?php echo $this->render('_partial/menu.phtml');?>
	<!-- CONTENT -->
	<div class="container">
		<div class="main-content clearfix">
            <div class="tile-area no-padding clearfix">
                <div class="tile-group no-margin no-padding clearfix" style="width: 100%">
                    <div class="tile double quadro-vertical bg-gray ol-transparent" style="float: right; ">
                        <div class="tile-content">
                            <div class="brand">
                                <span class="label fg-white">ads here...</span>
                            </div>
                        </div>
                    </div>

                    <div class="tile quadro double-vertical ol-transparent">
                        <div class="tile-content">
                            <div class="carousel" data-role="carousel" data-height="100%" data-width="100%" data-controls="false">
                                <div class="slide">
                                    <img src="images/1.jpg" />
                                </div>
                                <div class="slide">
                                    <img src="images/2.jpg" />
                                </div>
                                <div class="slide">
                                    <img src="images/3.jpg" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tile bg-lightBlue ol-transparent">
                        <div class="tile-content icon">
                            <span class="icon-windows"></span>
                        </div>
                    </div>
                    <div class="tile bg-orange ol-transparent">
                        <div class="tile-content icon">
                            <span class="icon-music"></span>
                        </div>
                    </div>
                    <div class="tile ol-transparent bg-teal">
                        <div class="tile-content icon">
                            <span class="icon-facebook"></span>
                        </div>
                    </div>
                    <div class="tile ol-transparent bg-green">
                        <div class="tile-content icon">
                            <span class="icon-twitter"></span>
                        </div>
                    </div>

                    <div class="tile triple double-vertical ol-transparent bg-white">
                        <div class="tile-content">
                            <div class="panel no-border">
                                <div class="panel-header bg-darkRed fg-white">news</div>
                                <div class="panel-content fg-dark nlp nrp">
                                    <img src="images/jeki_chan.jpg" class="place-left margin10 nlm ntm size2">
                                    <strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry.
                                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                                    Lorem Ipsum has been the industry's standard dummy text.
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tile triple double-vertical ol-transparent bg-white">
                        <div class="tile-content">
                            <div class="panel no-border">
                                <div class="panel-header bg-pink fg-white">entertainment</div>
                                <div class="panel-content fg-dark nlp nrp">
                                    <img src="images/jek_vorobey.jpg" class="place-left margin10 nlm ntm size2">
                                    <strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry.
                                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                                    Lorem Ipsum has been the industry's standard dummy text.
                                </div>
                            </div>
                        </div>
                    </div>
                </div> <!-- End first group -->

                <div class="tile-group no-margin no-padding clearfix" style="width: 100%">
<!--                     <div class="tile double ol-transparent"></div> -->
<!--                     <div class="tile double ol-transparent"></div> -->
<!--                     <div class="tile double ol-transparent"></div> -->
<!--                     <div class="tile double ol-transparent"></div> -->
<!--                 </div> -->

                <div class="tile-group no-margin no-padding1 clearfix" style="width: 100%;">
                    <a href="#"><span class="tile-group-title fg-orange">NEWS <span class="icon-arrow-right-5"></span></span></a>
                    <div class="tile quadro double-vertical ol-transparent"></div>
                    <div class="tile double ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile double ol-transparent"></div>
                </div>

                <div class="tile-group no-margin no-padding1 clearfix" style="width: 100%;">
                    <a href="#"><span class="tile-group-title fg-cobalt">SPORT <span class="icon-arrow-right-5"></span></span></a>
                    <div class="tile quadro double-vertical ol-transparent"></div>
                    <div class="tile double ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile double ol-transparent"></div>
                </div>
            </div>
        </div> <!-- End of tiles -->
	</div>
</body>
</html>