<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<!-- CSS -->
	<link type="text/css" rel="stylesheet" href="/resources/metro/css/metro-bootstrap.css">
	<link type="text/css" rel="stylesheet" href="/resources/metro/css/metro-bootstrap-responsive.css">
	<link type="text/css" rel="stylesheet" href="/resources/metro/min/iconFont.min.css" >
	<!-- JS -->
	<script type="text/javascript" src="/resources/metro/js/metro-dropdown.js"></script>
</head>

<!-- BODY -->
<body class="metro">
	<?php echo $this->render('_partial/header.phtml');?>
	<?php echo $this->render('_partial/menu.phtml');?>
</body>
<!-- END BODY -->
</html>