<div class="tile-area no-padding clearfix">

                <div class="tile-group no-margin no-padding clearfix" style="width: 100%">
                    <div class="tile double ol-transparent">
                    	<div class="title-content image">
                    		<img src="/resources/metro/images/girl-01.jpg" class="span4">
                    	</div>
                    	<div class="brand bg-dark opacity">
                    		<span class="text">Nhã Uyên - 9999 điểm</span>
                    	</div>
                    </div>
                    <div class="tile double ol-transparent">
                    	<div class="title-content image">
                    		<img src="/resources/metro/images/girl-03.jpg" class="span4">
                    	</div>
                    	<div class="brand bg-dark opacity">
                    		<span class="text">Uyển Nhi - 9998 điểm</span>
                    	</div>
                    </div>
                    <div class="tile double ol-transparent">
                    	<div class="title-content image">
                    		<img src="/resources/metro/images/girl-02.jpg" class="span4">
                    	</div>
                    	<div class="brand bg-dark opacity">
                    		<span class="text">Hương Ly - 9997 điểm</span>
                    	</div>
                    </div>
                    <div class="tile ol-transparent">
                    	<div class="title-content image">
                    		<img src="/resources/metro/images/girl120-01.jpg">
                    	</div>
                    	<div class="brand bg-dark opacity">
                    		<span class="text">Thục Quyên - 9996 điểm</span>
                    	</div>
                    </div>
                    <div class="tile ol-transparent">
                    	<div class="title-content image">
                    		<img src="/resources/metro/images/boy120-01.jpg">
                    	</div>
                    	<div class="brand bg-dark opacity">
                    		<span class="text">Matt - 9995 điểm</span>
                    	</div>
                    </div>
                </div>

                <div class="tile-group no-margin no-padding1 clearfix" style="width: 100%;">
                    <a href="#"><span class="tile-group-title fg-orange">Trắc nghiệm lớp 12 <span class="icon-arrow-right-5"></span></span></a>
                    <div class="tile quadro double-vertical ol-transparent">
                    	<div class="title-content image">
                    		<img src="/resources/metro/images/hoahoc2.jpg" class="span8">
                    	</div>
                    	<div class="brand bg-dark opacity">
                    		<span class="text">Bài trắc nghiệm số 69: Kim loại kiềm</span>
                    	</div>
                    </div>
                    <div class="tile double ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile double ol-transparent"></div>
                </div>

                <div class="tile-group no-margin no-padding1 clearfix" style="width: 100%;">
                    <a href="#"><span class="tile-group-title fg-cobalt">Trắc nghiệm lớp 11 <span class="icon-arrow-right-5"></span></span></a>
                    <div class="tile quadro double-vertical ol-transparent"></div>
                    <div class="tile double ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile double ol-transparent"></div>
                </div>
                
                <div class="tile-group no-margin no-padding1 clearfix" style="width: 100%;">
                    <a href="#"><span class="tile-group-title fg-yellow">Trắc nghiệm lớp 10 <span class="icon-arrow-right-5"></span></span></a>
                    <div class="tile quadro double-vertical ol-transparent"></div>
                    <div class="tile double ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile ol-transparent"></div>
                    <div class="tile double ol-transparent"></div>
                </div>
            </div>