<div class="bg-blue">
	<div class="container" style="padding: 10px 0;">
		<div class="grid no-margin">
	        <div class="row no-margin">
	            <div class="span6 padding10">
					<h3 class="fg-white">Trắc nghiệm cấp 3</h3>
	                <p class="fg-white">Đồ án tốt nghiệp khóa học lập trình Zend framework</p>
	            </div>
	            <div class="span3 padding10">
	            	<a class="button danger " style="width: 100%; margin-bottom: 5px" href="/home">Trang chủ</a>
	                <a class="button success " style="width: 100%; margin-bottom: 5px"  href="/about">Về tác giả</a>
	                <a class="button warning " style="width: 100%; margin-bottom: 5px"  href="/contact">Liên hệ</a>
				</div>            
			</div>            
		</div>                
	</div>            
	
	<div class="container tertiary-text bg-dark fg-white" style="padding: 10px">
		Copyright &copy; Anh Nguyễn 2014 - <a href="mailto:anhnv1310@gmail.com" class="fg-yellow">anhnv1310@gmail.com</a>
	</div>
</div>